### PR TITLE
Multiple encode jwt auth

### PR DESCRIPTION
**Pull request by aaronshiel**

### CODE REVIEW

**Comment by mbsimonovic** [comment]
didnt i already made this work for multiple api keys? API_KEY can be a comma-separated list of different keys (prod, dev, stage, ...)

**Comment by aaronshiel** [comment]
> didnt i already made this work for multiple api keys? API_KEY can be a comma-separated list of different keys (prod, dev, stage, ...)

yes, but I'm adding JWT token authorization aswell

**Comment by mbsimonovic** [comment]
ah right, jwt. but you shouldn't have to worry about keys from different environments, so a single key/secret should be enough.

**Comment by aaronshiel** [comment]
> ah right, jwt. but you shouldn't have to worry about keys from different environments, so a single key/secret should be enough.

since we don't have a dev environment yet, qa has to accept both qa and dev jwt's

**Comment by mbsimonovic** [comment]
but we do - newdev?

**Comment by mbsimonovic** [comment]
perhaps  you can use a single variable that is a list? having environment name seems fragile

**Pull request merged**
